### ISSUE TITLE
Add link to ORKG position paper to homepage

### ISSUE THREAD

**Issue by clange** [ORKG/ORKG.github.io#1]
The homepage should have a link to https://www.tib.eu/en/service/news/details/tib-publishes-position-paper-on-open-research-knowledge-graph/ and/or to the actual position paper.

**Comment by np00** [comment]
Fixed: https://github.com/ORKG/ORKG.github.io/commit/b9b7ef768b159770b6a8643b082cd6bde0bda2ad
and added a few more links. 

(I just wanted to test an auto issue closing, by using the right keywords in the commit message, but either it takes some time by GitHub to recognize it, or I failed :'( )
